# Generated by Django 2.2.5 on 2020-02-19 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_remove_blog_readed_num'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReadNum',
        ),
    ]
